version: '3.8'

services:
  campuswa-admin-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "55555:55555"
    volumes:
      # Monter seulement le code source, pas node_modules
      - ./src:/app/src
      - ./public:/app/public
      - ./index.html:/app/index.html
      - ./vite.config.ts:/app/vite.config.ts
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.app.json:/app/tsconfig.app.json
      - ./tsconfig.node.json:/app/tsconfig.node.json
      - ./tailwind.config.ts:/app/tailwind.config.ts
      - ./postcss.config.js:/app/postcss.config.js
      - ./components.json:/app/components.json
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    networks:
      - campuswa-dev-network

networks:
  campuswa-dev-network:
    driver: bridge