version: '3.8'

services:
  campuswa-admin-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "55555:55555"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3001
    restart: unless-stopped
    networks:
      - campuswa-dev-network

networks:
  campuswa-dev-network:
    driver: bridge