# Utiliser l'image de base Node.js
FROM node:18-alpine

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Installer pnpm globalement
RUN npm install -g pnpm

# Copier les fichiers de gestion des paquets essentiels (uniquement package.json)
COPY package.json ./

# Installer les dépendances en utilisant pnpm
# Cette commande installe les dépendances en se basant sur le package.json
RUN pnpm install

# Copier le reste du code de l'application
COPY . .

# Exposer le port de l'application
EXPOSE 55555

# Lancer le serveur de développement avec pnpm
CMD ["pnpm", "run", "dev", "--", "--host", "0.0.0.0"]