version: '3.8'

services:
  campuswa-admin-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3001
    restart: unless-stopped
    networks:
      - campuswa-dev-network

  postgres-dev:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: campuswa_dev
      POSTGRES_USER: campuswa_dev
      POSTGRES_PASSWORD: campuswa_dev_password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped
    networks:
      - campuswa-dev-network

  redis-dev:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_dev_data:/data
    restart: unless-stopped
    networks:
      - campuswa-dev-network

volumes:
  postgres_dev_data:
  redis_dev_data:

networks:
  campuswa-dev-network:
    driver: bridge