version: '3.8'

services:
  campuswa-admin:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - campuswa-dev-network

networks:
  campuswa-dev-network:
    driver: bridge